In [2]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import datetime
from dateutil.relativedelta import relativedelta

In [3]:
processed_table_6169 = pd.read_csv('./data/processed_table.csv')

processed_table_7244 = pd.read_csv('./data/processed_table_7244.csv')

In [3]:
processed_table_6169 = processed_table_6169.drop('Unnamed: 0',  axis = 1)
processed_table_6169 = processed_table_6169.fillna(0.0)
processed_table_6169.head()

,donorID,province,region,gender,language,number_of_campaigns,total_amount,Q1_Donations,Q2_Donations,Q3_Donations,...,Q3_Amount,Q4_Amount,Q1_Max,Q2_Max,Q3_Max,Q4_Max,age,age-group,amount,has_contributed
0,100001,Flemish Brabant,Flanders,F,NL,12.0,178.49,3.0,3.0,1.0,...,7.44,63.87,20.0,30.00,7.44,24.79,51,50,0.0,0
1,100002,Antwerp,Flanders,M,NL,1.0,20.00,1.0,0.0,0.0,...,0.00,0.00,20.0,0.00,0.00,0.00,66,60,0.0,0
2,100004,Brussels,Brussels,F,FR,26.0,716.22,8.0,4.0,4.0,...,99.16,283.11,30.0,30.00,24.79,49.58,66,60,0.0,0
3,100008,Flemish Brabant,Flanders,M,FR,3.0,124.37,0.0,1.0,0.0,...,0.00,74.79,0.0,49.58,0.00,50.00,81,80,0.0,0
4,100009,Brussels,Brussels,M,FR,19.0,326.78,5.0,4.0,4.0,...,95.00,84.61,20.0,25.00,25.00,20.00,86,80,0.0,0

In [4]:
processed_table_7244 = processed_table_7244.drop('Unnamed: 0',  axis = 1)
processed_table_7244 = processed_table_6169.fillna(0.0)
processed_table_7244.head()

,donorID,province,region,gender,language,number_of_campaigns,total_amount,Q1_Donations,Q2_Donations,Q3_Donations,...,Q3_Amount,Q4_Amount,Q1_Max,Q2_Max,Q3_Max,Q4_Max,age,age-group,amount,has_contributed
0,100001,Flemish Brabant,Flanders,F,NL,12.0,178.49,3.0,3.0,1.0,...,7.44,63.87,20.0,30.00,7.44,24.79,51,50,0.0,0
1,100002,Antwerp,Flanders,M,NL,1.0,20.00,1.0,0.0,0.0,...,0.00,0.00,20.0,0.00,0.00,0.00,66,60,0.0,0
2,100004,Brussels,Brussels,F,FR,26.0,716.22,8.0,4.0,4.0,...,99.16,283.11,30.0,30.00,24.79,49.58,66,60,0.0,0
3,100008,Flemish Brabant,Flanders,M,FR,3.0,124.37,0.0,1.0,0.0,...,0.00,74.79,0.0,49.58,0.00,50.00,81,80,0.0,0
4,100009,Brussels,Brussels,M,FR,19.0,326.78,5.0,4.0,4.0,...,95.00,84.61,20.0,25.00,25.00,20.00,86,80,0.0,0

In [5]:
# machine learning
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score
import queue
import threading

In [6]:
def logistic_regression(column, X_train, X_TEST, Y_train, Y_TEST):
    logreg = LogisticRegression(random_state=123)
    logreg.fit(X_train, X_TEST)
    # predict probabilities
    pred_train = logreg.predict(X_train)
    pred_test = logreg.predict(Y_train)

    # evaluate predictions
    mlp_acc_train = accuracy_score(X_TEST, pred_train)
    mlp_acc_test = accuracy_score(Y_TEST, pred_test)

    mlp_roc_train = roc_auc_score(X_TEST, logreg.predict_proba(X_train)[:,1])
    mlp_roc_test = roc_auc_score(Y_TEST,  logreg.predict_proba(Y_train)[:,1])

    eval_dict = {"Acc_train": mlp_acc_train, "Acc_test": mlp_acc_test, "roc_train":  mlp_roc_train,"roc_test": mlp_roc_test}
    return eval_dict

In [133]:

encoder = LabelEncoder()

for column in processed_table_6169.columns[0:]:
    if processed_table_6169[column].dtype == object:
        processed_table_6169[column] = encoder.fit_transform(processed_table_6169[column])
for column in processed_table_7244.columns[0:]:
    if processed_table_7244[column].dtype == object:
            processed_table_7244[column] = encoder.fit_transform(processed_table_7244[column])

In [134]:
    #q = queue.Queue()
    X_train = pd.DataFrame(processed_table_6169['number_of_campaigns'])
    X_test = processed_table_6169["has_contributed"]
    Y_train = pd.DataFrame(processed_table_7244['number_of_campaigns'])
    Y_test = processed_table_7244["has_contributed"]
    t = logistic_regression('number_of_campaigns', X_train,X_test ,Y_train,Y_test)
    print(t)

{'Acc_train': 0.9789528015140219, 'Acc_test': 0.9789528015140219, 'roc_train': 0.5445697432754054, 'roc_test': 0.5445697432754054}

In [135]:
len(processed_table_6169.columns)

35

In [4]:
import itertools
test = processed_table_6169.columns
combinations = []
for L in range(0, len(test)):
   perm_iterator = itertools.combinations(test, L)
   for item in perm_iterator:
      combinations.append(item)


# for L in range(0, len(test)):
#     for subset in itertools.combinations(test, L):
#         combinations.append(subset)

print(combinations)

TypeError: combinations() missing required argument 'r' (pos 2)

In [8]:

free -m

NameError: name 'free' is not defined

In [167]:
evaldic = {}
for combination in combinations[1:]:
    l = []
    column =  combination[0]
    l.append(column)
    X_train = processed_table_6169[l]
    X_Test = processed_table_6169["has_contributed"]
    Y_train = processed_table_7244[l]
    Y_Test = processed_table_7244["has_contributed"]
    evaldic[combination] = logistic_regression(l, X_train,X_Test,Y_train, Y_Test)

for key in evaldic.keys():
    print(key)
    print(evaldic[key])

('gender',)
{'Acc_train': 0.9789528015140219, 'Acc_test': 0.9789528015140219, 'roc_train': 0.6713434742980101, 'roc_test': 0.6713434742980101}
('province',)
{'Acc_train': 0.9789528015140219, 'Acc_test': 0.9789528015140219, 'roc_train': 0.5019517326475851, 'roc_test': 0.5019517326475851}
('region',)
{'Acc_train': 0.9789528015140219, 'Acc_test': 0.9789528015140219, 'roc_train': 0.5034725181932387, 'roc_test': 0.5034725181932387}
('language',)
{'Acc_train': 0.9789528015140219, 'Acc_test': 0.9789528015140219, 'roc_train': 0.5139013462757136, 'roc_test': 0.5139013462757136}
('gender', 'province')
{'Acc_train': 0.9789528015140219, 'Acc_test': 0.9789528015140219, 'roc_train': 0.6713434742980101, 'roc_test': 0.6713434742980101}
('gender', 'region')
{'Acc_train': 0.9789528015140219, 'Acc_test': 0.9789528015140219, 'roc_train': 0.6713434742980101, 'roc_test': 0.6713434742980101}
('gender', 'language')
{'Acc_train': 0.9789528015140219, 'Acc_test': 0.9789528015140219, 'roc_train': 0.6713434742980101, 'roc_test': 0.6713434742980101}
('province', 'region')
{'Acc_train': 0.9789528015140219, 'Acc_test': 0.9789528015140219, 'roc_train': 0.5019517326475851, 'roc_test': 0.5019517326475851}
('province', 'language')
{'Acc_train': 0.9789528015140219, 'Acc_test': 0.9789528015140219, 'roc_train': 0.5019517326475851, 'roc_test': 0.5019517326475851}
('region', 'language')
{'Acc_train': 0.9789528015140219, 'Acc_test': 0.9789528015140219, 'roc_train': 0.5034725181932387, 'roc_test': 0.5034725181932387}
('gender', 'province', 'region')
{'Acc_train': 0.9789528015140219, 'Acc_test': 0.9789528015140219, 'roc_train': 0.6713434742980101, 'roc_test': 0.6713434742980101}
('gender', 'province', 'language')
{'Acc_train': 0.9789528015140219, 'Acc_test': 0.9789528015140219, 'roc_train': 0.6713434742980101, 'roc_test': 0.6713434742980101}
('gender', 'region', 'language')
{'Acc_train': 0.9789528015140219, 'Acc_test': 0.9789528015140219, 'roc_train': 0.6713434742980101, 'roc_test': 0.6713434742980101}
('province', 'region', 'language')
{'Acc_train': 0.9789528015140219, 'Acc_test': 0.9789528015140219, 'roc_train': 0.5019517326475851, 'roc_test': 0.5019517326475851}